[tool.poetry]
name = "pplab"
version = "0.1.0"
description = ""
authors = ["maxlevytskyi2004@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.7.6"
Flask = "^2.2.2"
waitress = "^2.1.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
