"""empty message

Revision ID: 01499a8e0874
Revises: 
Create Date: 2022-10-30 14:53:04.756179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01499a8e0874'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audience',
    sa.Column('audience_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=45), nullable=True),
    sa.Column('datatime', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('audience_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=45), nullable=True),
    sa.Column('firstname', sa.String(length=45), nullable=True),
    sa.Column('lastname', sa.String(length=45), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=45), nullable=True),
    sa.Column('phone', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('order',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DATE(), nullable=True),
    sa.Column('end_time', sa.DATE(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('audience_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['audience_id'], ['audience.audience_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    op.drop_table('user')
    op.drop_table('audience')
    # ### end Alembic commands ###
